name: vinni
favicon: null
layout_spectrum: 0.09556
typography_spectrum: 0.38127
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#60a071'
    - '#015762'
    - '#b15400'
    - '#e9c25f'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
